name: golmi
channels:
  - conda-forge
  - defaults
dependencies:
  - chardet
  - flask
  - flask-cors
  - markupsafe
  - werkzeug
  - requests
  - idna
  - itsdangerous
  - python-engineio
  - dnspython
  - click
  - python
  - jinja2
  - python-socketio
  - flask-socketio
  - certifi
  - bidict
  - eventlet
  - urllib3
  - six
  - greenlet
  - ipython
  - numpy
  - matplotlib
  - pip
  - pip:
    - python-socketio[client]